name: CI Pipeline

on:
  push:
    branches:
      - main # Triggers on pushes to the main branch
  pull_request:
    branches:
      - main # Triggers on pull requests targeting the main branch

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript check
        run: npm run build # This checks for TypeScript errors and builds the project

      - name: Run ESLint
        run: npm run lint

      - name: Run Unit Tests (Optional, but recommended)
        run: |
          # if any common test filenames exist, run tests; otherwise skip
          if ls **/*.{test,spec}.{js,jsx,ts,tsx} 1> /dev/null 2>&1; then
            echo "Test files detected, running npm test..."
            npm test
          else
            echo "No test files found; skipping tests."
          fi
